title:        /dev/null 
tagline:      "/dev/null by Martin Biermann"
url:          http://devnull.martinbiermann.com
author:
  name:       "Martin Biermann"
  email:      "info@martinbiermann.com"
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
